Deploy Package Operator to Hosted Clusters
package-operator/package-operator pull request #1034
Opened 2024-03-20 11:33 UTC by kostola

### Summary

### Change Type

### Check List Before Merging

- [ ] This PR passes all pre-commit hook validations.
- [ ] This PR is fully tested and regression tests are included.
- [ ] Relevant documentation has been updated.

### Additional Information

2024-03-20 15:08 UTC, kostola commented
Requires #959 to complete integration tests

2024-04-03 16:44 UTC, eqrx requested changes

2024-04-03 16:44 UTC, eqrx commented on .vscode/launch.json
Is it intended to commit this? If so, lets call it smth more explicit than "Launch" since it specifically creates a hosted cluster. Maybe we could even add other targets to make it easier to develop from vscode

2024-04-04 09:27 UTC, kostola commented on .vscode/launch.json
@erdii you added this file...I can't answer this comment because I don't use VSCode with Go

2024-04-04 16:00 UTC, kostola commented on cmd/build/package.go
> +	if err := mgr.SerialDeps(
exactly...I didn't see any CI error anymore after changing this

2024-04-05 11:07 UTC, eqrx commented on .vscode/launch.json
remove it please and i approve it:)

2024-04-10 14:12 UTC, kostola commented on .vscode/launch.json
removed

2024-04-10 14:12 UTC, kostola commented on config/packages/package-operator/.test-fixtures/openshift-with-proxy/package-operator-manager.Deployment.yaml
> +          value: ""
fixed

2024-04-10 14:13 UTC, kostola commented on install.yaml
> +          value: "quay.io/package-operator/package-operator-package:latest"
I'll keep `latest` here since it was there before

2024-04-10 14:13 UTC, kostola commented on internal/adapters/package.go
> +			Image:                     a.Package.Spec.Image,
fixed

2024-04-10 14:14 UTC, kostola commented on internal/controllers/hostedclusters/hostedcluster_controller.go
> +	hostedClusterTolerations []corev1.Toleration
not needed anymore

2024-04-10 14:26 UTC, kostola commented on cmd/build/test.go
> +	eErr2 := hypershiftHostedCluster.ExportLogs(filepath.Join(cacheDir, "integration_hypershift", "logs"))
I used the same pattern as the upper part of the test, let's keep as it is for now

2024-04-10 14:28 UTC, kostola commented on internal/controllers/hostedclusters/hostedcluster_controller.go
> +			return ctrl.Result{}, fmt.Errorf("deleting outdated Package: %w", err)
not needed anymore

2024-04-10 14:30 UTC, kostola commented on cmd/build/generate.go
> -		case schema.GroupKind{Group: "apps", Kind: "Deployment"},
it's grouped in the `default` case now

2024-04-10 15:54 UTC, eqrx approved these changes
lgtm but please wait for the review by @thetechnick

2024-04-11 11:48 UTC, thetechnick approved these changes
lgtm as well :+1:

2024-04-11 12:15 UTC, merged