[integration] bugfix for PKO-85: correctly attribute (Cluster)ObjectSlices to their owning (Cluster)ObjectSets
package-operator/package-operator pull request #1118
Opened 2024-04-24 12:23 UTC by erdii

Signed-off-by: Josh Gwosdz <jgwosdz@redhat.com>

### Summary

### Change Type

Bug Fix

### Check List Before Merging

- [x] This PR passes all pre-commit hook validations.
- [ ] This PR is fully tested and regression tests are included.
- [x] Relevant documentation has been updated.

### Additional Information

2024-04-25 10:32 UTC, eqrx requested changes

2024-04-25 10:32 UTC, eqrx commented on integration/package-operator/package_test.go
> +		if len(namespace) != 0 {
```suggestion
		if len(namespace) != "" {
```

2024-04-25 10:32 UTC, eqrx commented on integration/package-operator/package_test.go
> +		if len(namespace) != 0 {
```suggestion
		if len(namespace) != "" {
```

2024-04-25 13:03 UTC, eqrx approved these changes

2024-04-26 13:32 UTC, erdii commented
https://github.com/package-operator/package-operator/actions/runs/8848911618/job/24299671181?pr=1118#step:5:375

> 📦 package-operator.run/integration/package-operator
> panic: PKO_TEST_SUCCESS_PACKAGE_IMAGE not set!

> goroutine 1 [running]:
> package-operator.run/integration/package-operator.init.0()
> 	/home/runner/work/package-operator/package-operator/integration/package-operator/environment.go:61 +0x72d

2024-04-26 14:28 UTC, erdii commented
I have solved the above problem by adding `//go:build integration || integration_hypershift` to the top of the renamed file.

2024-04-26 14:44 UTC, erdii commented
> codecov/project — 60.14% (-0.88%) compared to b8552e1

I vote for "force merge" after accepting review.

2024-04-30 13:03 UTC, eqrx approved these changes

2024-04-30 15:59 UTC, merged