PKO - Comply with restricted PSA enforcement
package-operator/package-operator pull request #1183
Opened 2024-05-19 22:07 UTC by venkateshsredhat

### Summary
this resolves https://issues.redhat.com/browse/PKO-37 
### Change Type

### Check List Before Merging

- [ ] This PR passes all pre-commit hook validations.
- [ ] This PR is fully tested and regression tests are included.
- [ ] Relevant documentation has been updated.

### Additional Information

2024-05-28 12:33 UTC, venkateshsredhat commented
Tested it locally , currently no warnings for any pko related namespaces with enforcing "restricted"

`[ves@ves-thinkpadp1gen4i package-operator ]$ kubectl label --dry-run=server --overwrite ns --all pod-security.kubernetes.io/enforce=restricted
namespace/default labeled (server dry run)
namespace/default-pko-hs-hc labeled (server dry run)
Warning: existing pods in namespace "dev-registry" violate the new PodSecurity enforce level "restricted:latest"
Warning: dev-registry-cd764f6d6-kstm8: hostPort, allowPrivilegeEscalation != false, unrestricted capabilities, runAsNonRoot != true, seccompProfile
namespace/dev-registry labeled (server dry run)
namespace/kube-node-lease labeled (server dry run)
namespace/kube-public labeled (server dry run)
Warning: existing pods in namespace "kube-system" violate the new PodSecurity enforce level "restricted:latest"
Warning: coredns-76f75df574-84dhz (and 1 other pod): runAsNonRoot != true, seccompProfile
Warning: etcd-pko-control-plane (and 3 other pods): host namespaces, allowPrivilegeEscalation != false, unrestricted capabilities, restricted volume types, runAsNonRoot != true
Warning: kindnet-h7lht: host namespaces, allowPrivilegeEscalation != false, unrestricted capabilities, restricted volume types, runAsNonRoot != true, seccompProfile
Warning: kube-proxy-gk6bv: host namespaces, privileged, allowPrivilegeEscalation != false, unrestricted capabilities, restricted volume types, runAsNonRoot != true, seccompProfile
namespace/kube-system labeled (server dry run)
Warning: existing pods in namespace "local-path-storage" violate the new PodSecurity enforce level "restricted:latest"
Warning: local-path-provisioner-7577fdbbfb-9zxmw: allowPrivilegeEscalation != false, unrestricted capabilities, runAsNonRoot != true, seccompProfile
namespace/local-path-storage labeled (server dry run)
namespace/package-operator-system labeled (server dry run)
`

2024-05-29 03:36 UTC, venkateshsredhat commented
/retest

2024-05-31 12:12 UTC, erdii commented
This looks good to me overall. Nice work! :)

I'm cautious about a needed validation which can also serve as a regressiion test: How do we know that the `restricted` pod security standard in the pko namespace is actually enforced during the integration tests?

I think it would make sense to explore adding an integration test that creates a pod object, scheduling a pod without adding a security context, thus violating the security standard, and let the integration test verify that the pod is not allowed to run because of the violation.

2024-05-31 12:12 UTC, erdii requested changes
This looks good to me overall. Nice work! :)

I'm cautious about a needed validation which can also serve as a regressiion test: How do we know that the `restricted` pod security standard in the pko namespace is actually enforced during the integration tests?

I think it would make sense to explore adding an integration test that creates a pod object, scheduling a pod without adding a security context, thus violating the security standard, and let the integration test verify that the pod is not allowed to run because of the violation.

2024-05-31 12:55 UTC, venkateshsredhat commented
Thanks @erdii  , Let me take a look and try to cover it in Integration test .

2024-06-03 20:04 UTC, venkateshsredhat commented
Based on your previous suggestion in the PR adding integration test to cover this :
Local test output :
=== RUN   TestRestrictedPolicyPod_creation_
    restrictedpolicy_test.go:44: pods "testing-policy-pod" is forbidden: violates PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "my-container" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "my-container" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "my-container" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "my-container" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
    wait.go:193: "level"=0 "msg"="waiting 20s for /v1, Kind=Pod package-operator-system/testing-policy-pod to be gone..."
--- PASS: TestRestrictedPolicyPod_creation_ (0.01s)
PASS

2024-06-04 08:51 UTC, erdii requested changes

2024-06-04 08:51 UTC, erdii commented on integration/package-operator/restrictedpolicy_test.go
> +func TestRestrictedPolicyPod_creation_(t *testing.T) {
```suggestion
func TestRestrictedPolicyPodCreation(t *testing.T) {
```

2024-06-04 08:51 UTC, erdii commented on integration/package-operator/restrictedpolicy_test.go
> +					},
```suggestion
```

This can be dropped as we don't need any of nginx' actual functionality.

2024-06-04 08:51 UTC, erdii commented on integration/package-operator/restrictedpolicy_test.go
> +	require.Error(t, err)
The error should be confirmed to be an error resulting of the Pod Security Standard violation.

2024-06-04 08:56 UTC, erdii requested changes

2024-06-04 08:56 UTC, erdii commented on integration/package-operator/restrictedpolicy_test.go
> +
```suggestion

// This test validates that the package-operator namespace is configured to actually enforce the restricted PSS.
```

2024-06-04 08:56 UTC, erdii commented on integration/package-operator/restrictedpolicy_test.go
> +	t.Log(err)
```suggestion
```

2024-06-04 12:16 UTC, erdii requested changes

2024-06-04 12:16 UTC, erdii commented on integration/package-operator/restrictedpolicy_test.go
> -	"github.com/stretchr/testify/require"
Please move the import back into this block :sweat_smile:

2024-06-04 12:16 UTC, erdii commented on integration/package-operator/restrictedpolicy_test.go
> +	require.ErrorContains(t, err, " forbidden: violates PodSecurity \"restricted:latest\": ")
```suggestion
	require.ErrorContains(t, err, `forbidden: violates PodSecurity "restricted:latest": `)
```

2024-06-04 14:29 UTC, erdii submitted a review, later dismissed

2024-06-20 10:33 UTC, thetechnick approved these changes

2024-06-20 10:45 UTC, merged