[PKO-136] Pause feature for (Cluster)Package API
package-operator/package-operator pull request #1567
Opened 2024-11-27 10:49 UTC by radimous

### Summary

### Change Type
New Feature

### Jira
[PKO-136](https://issues.redhat.com/browse/PKO-136)

### Check List Before Merging

- [ ] This PR passes all pre-commit hook validations.
- [ ] This PR is fully tested and regression tests are included.
- [ ] Relevant documentation has been updated.
- [ ] The commits in this PR follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
      standard.

### Additional Information

Depends on #1535

2025-02-03 12:40 UTC, thetechnick submitted a review, later dismissed
Good work! :+1:

2025-02-03 16:29 UTC, pbabic-redhat requested changes
Great work!

I left a couple of comments. Please let me know if I can help with anything. :)

2025-02-03 16:29 UTC, pbabic-redhat commented on internal/adapters/package.go
> +	if meta.IsStatusConditionTrue(*pkg.GetConditions(), string(corev1alpha1.PackagePaused)) {
I think this is not needed.
```suggestion
	if meta.IsStatusConditionTrue(*pkg.GetConditions(), corev1alpha1.PackagePaused) {
```

2025-02-03 16:29 UTC, pbabic-redhat commented on internal/controllers/packages/package_controller_test.go
> +package packages
The unit tests here look really good, thanks! But there is no test for the pause feature. I think that would be nice to have.

2025-02-04 13:33 UTC, pbabic-redhat commented on config/packages/test-stub-pause/manifest.yaml
> +apiVersion: manifests.package-operator.run/v1alpha1
This is also a detail. Please consider it more of a feedback rather than a must have change. :grin:

2025-02-06 16:16 UTC, erdii commented on internal/controllers/packages/object_deployment_status_reconciler.go
> +		meta.RemoveStatusCondition(packageObj.GetConditions(), corev1alpha1.PackagePaused)
I don't think we should remove the status condition here. We should keep it and explicitly set it to false.

2025-02-06 16:29 UTC, erdii requested changes
lgtm otherwise!

2025-02-06 16:33 UTC, erdii commented on internal/controllers/packages/object_deployment_status_reconciler.go
> +		meta.RemoveStatusCondition(packageObj.GetConditions(), corev1alpha1.PackagePaused)
ah whatever - i don't need to be nitpicky

2025-02-06 16:33 UTC, erdii approved these changes

2025-02-10 09:39 UTC, merged