[PKO-169] Move repo_test.go to integration tests
package-operator/package-operator pull request #1574
Opened 2024-12-04 08:29 UTC by kostola

### Summary

[JIRA Task](https://issues.redhat.com/browse/PKO-169)

#### Existing issues
* `repo_test.go` was included as unit test but is in fact an integration test because it tries to connect to an external registry (originally `quay.io`).
* the test could produce different results if the user running it was logged or not to `quay.io`.

#### What this PR does
* Move `repo_test.go` under integration tests.
* Configure `repo_test.go` to use the KinD internal registry (that we already configure) instead of `quay.io`.
* Expand the internal registry configuration adding a proxy that enables authentication, while keeping the old usage intact (`localhost:5001` still points to the plain registry, `localhost:5002` points to the authenticated registry via proxy). This allows to test unauthenticated access.

### Change Type

Bug Fix

### Check List Before Merging

- [x] This PR passes all pre-commit hook validations.
- [x] This PR is fully tested and regression tests are included.
- [ ] Relevant documentation has been updated.
- [ ] The commits in this PR follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
      standard.

### Additional Information

2024-12-05 16:25 UTC, pbabic-redhat commented
Hey @kostola,
I tried to authenticate to the registry proxy and got the following error:
```bash
$ ./.cache/deps/bin/crane auth login localhost:5002 -u registry -p foobar
Error: error storing credentials - err: exit status 1, out: `error storing credentials - err: exit status 1, out: `pass not initialized: exit status 1: Error: password store is empty. Try "pass init".``
```
Does it work for you?

2024-12-05 17:33 UTC, kostola commented
> Hey @kostola, I tried to authenticate to the registry proxy and got the following error:
> 
> ```shell
> $ ./.cache/deps/bin/crane auth login localhost:5002 -u registry -p foobar
> Error: error storing credentials - err: exit status 1, out: `error storing credentials - err: exit status 1, out: `pass not initialized: exit status 1: Error: password store is empty. Try "pass init".``
> ```
> 
> Does it work for you?

@pbabic-redhat This works for me:

```
$ podman login --tls-verify=false localhost:5002 -u registry -p foobar
Login Succeeded!
```

Yours looks like an error with some password store, rather than the login itself.

2024-12-06 09:01 UTC, kostola commented
@pbabic-redhat your command works as well for me:

```
$ .cache/deps/bin/crane auth login localhost:5002 -u registry -p foobar
2024/12/06 09:58:22 logged in via ~/.docker/config.json
```

imho this is another hint it's a problem with your password store

2024-12-09 10:25 UTC, pbabic-redhat reviewed
Hey @kostola,
sorry for the late reply. The PR looks good to me. Would you mind just updating the commit messages to conform to conventional commits (we spoke about it in the last retro/planning)? :slightly_smiling_face:

2024-12-09 11:37 UTC, pbabic-redhat requested changes
Oops, ticked the wrong box :sweat_smile:

2024-12-10 15:07 UTC, pbabic-redhat approved these changes
lgtm :rocket:

2024-12-11 10:23 UTC, merged