Add DynamicWatcher
package-operator/package-operator pull request #2
Opened 2022-07-27 21:47 UTC by thetechnick

Add basic DynamicWatcher component, as a pre-requisite for implementing the first controllers.

Signed-off-by: Nico Schieder <nschieder@redhat.com>

2022-07-29 14:41 UTC, garrettthomaskth commented on internal/dynamicwatcher/dynamic_watcher_test.go
> +	owners := dw.OwnersForNamespacedGKV(NamespacedGKV{
Does it make sense to pull out the repeated `NamespacedGKV` into a variable?

2022-07-29 14:48 UTC, garrettthomaskth commented on internal/dynamicwatcher/dynamic_watcher.go
> +// OwnerReference points to a single owner of an watch operation.
```suggestion
// OwnerReference points to a single owner of a watch operation.
```

2022-07-29 14:50 UTC, garrettthomaskth commented on internal/dynamicwatcher/dynamic_watcher_test.go
> +type RestMapperMock struct {
Maybe we should decide if want to define mocks before or after the tests, just to make everything a little more consistent

2022-07-29 15:02 UTC, garrettthomaskth commented on internal/dynamicwatcher/dynamic_watcher_test.go
> +		Return(&meta.RESTMapping{Resource: secretsGVR}, nil)
Do we have to test the mocks?

2022-07-29 16:29 UTC, garrettthomaskth commented on internal/dynamicwatcher/dynamic_watcher_test.go
> +	restMapper.AssertExpectations(t)
```suggestion
	restMapper.AssertExpectations(t)
	informerMock.AssertExpectations(t)
```

2022-08-01 08:50 UTC, garrettthomaskth commented on internal/dynamicwatcher/dynamic_watcher_test.go
> +	informerMock.On("Run", mock.Anything)
```suggestion
```

2022-08-01 13:39 UTC, garrettthomaskth commented on internal/dynamicwatcher/dynamic_watcher.go
> +type informer interface {
Just a question: Why not use one of the informers from the `client-go` package? https://pkg.go.dev/k8s.io/client-go/informers

2022-08-01 15:19 UTC, eqrx requested changes

2022-08-01 15:19 UTC, eqrx commented on internal/testutil/log.go
> +type Logger struct {
Remove this and use https://pkg.go.dev/github.com/go-logr/logr@v1.2.3/testr instead. logr already provides coupling with testing

2022-08-02 10:19 UTC, eqrx approved these changes

2022-08-02 22:22 UTC, merged