Rollout History command
package-operator/package-operator pull request #206
Opened 2023-03-01 11:05 UTC by roastdeer

As user of package operator I would like an easy way to list revisions of a Package or ObjectDeployment.

Today I can list revisions only by issuing a command like:
`kubectl get objectset --sort-by=.metadata.creationTimestamp`

But this becomes crowded quickly when multiple packages/objectdeployments exist in the same namespace.

Acceptance Criteria:

- New kubectl package rollout history command
- Output similar to kubectl rollout history deployment/my-nginx
- Works with Package/ClusterPackage/CusterObjectDeployment and ObjectDeployments
- Shows Change-Cause by printing the https://kubernetes.io/docs/reference/labels-annotations-taints/#change-cause annotation, if set

2023-03-02 21:36 UTC, thetechnick commented
/ok-to-test

2023-03-07 09:01 UTC, garrettthomaskth commented on cmd/kubectl-package/command/rolloutcmd/rollout_utils.go
> +func GetClusterPackageByName(ctx context.Context, c client.Client, name string) (*corev1alpha1.ClusterPackage, error) {
And for the list use `unstructured.UnstructuredList{}` and set it's GVK by adding "List" to kind. e.g. ConfigMap kind would become ConfigMapList

2023-04-04 09:47 UTC, eqrx approved these changes

2023-04-21 17:57 UTC, eqrx requested changes

2023-04-21 17:57 UTC, eqrx commented on cmd/kubectl-package/command/rolloutcmd/rollout_utils.go
> +func GetClusterObjectByName(ctx context.Context, c client.Client, name string, t interface{}) (interface{}, error) {
```
// In our call we implemented an type for this generic, just so you know, you can also inline it like here:
func GetClusterObjectByName[O v1alpha1.ClusterPackage | v1alpha1.ClusterObjectDeployment | v1alpha1.ClusterObjectSet](ctx context.Context, c client.Client, name string) (result O, err error) {
	// This is "a bit" magical, result has the generic type O, we take a pointer to it and tell go to interpret it as an interface (any is an alias for interface{}).
	// Then we switch over the type of this pointer an put a pointer with the concrete type into the variable concreteResultPtr.
	switch concreteResultPtr := any(&result).(type) {
	case *v1alpha1.ClusterPackage:
		var list v1alpha1.ClusterPackageList

		if err := c.List(ctx, &list); err != nil {
			// You can't really specify a default value of a generic so just hurl the already existing result upwards.
			return result, fmt.Errorf("getting cluster packages: %w", err)
		}

		for _, n := range list.Items {
			if name == n.Name {
				// concreteResultPtr is set to the correct concrete type so you can just assign it here.
				*concreteResultPtr = n

				// Naked return returns results and err.
				return
			}
		}

		// You just returned the default value and no error which requires caller to.
		return result, errors.NewNotFound(schema.GroupResource{Group: "TODO", Resource: "TODO"}, name)
	case *v1alpha1.ClusterObjectDeployment:
		var list v1alpha1.ClusterObjectDeploymentList

		if err := c.List(ctx, &list); err != nil {
			return result, fmt.Errorf("getting cluster object deployments: %w", err)
		}

		for _, n := range list.Items {
			if name == n.Name {
				*concreteResultPtr = n

				return
			}
		}

		return result, errors.NewNotFound(schema.GroupResource{Group: "TODO", Resource: "TODO"}, name)
	case *v1alpha1.ClusterObjectSet:
		var list v1alpha1.ClusterObjectSetList

		if err := c.List(ctx, &list); err != nil {
			return result, fmt.Errorf("getting cluster object sets: %w", err)
		}

		for _, n := range list.Items {
			if name == n.Name {
				*concreteResultPtr = n

				return
			}
		}

		return result, errors.NewNotFound(schema.GroupResource{Group: "TODO", Resource: "TODO"}, name)
	default:
		panic("unknown object type")
	}
}
```

2023-05-31 12:02 UTC, closed without merging