Fix unittest not reporting on stdout
package-operator/package-operator pull request #355
Opened 2023-08-02 13:29 UTC by thetechnick

### Summary

### Change Type
Bug Fix

### Check List Before Merging

- [ ] This PR passes all pre-commit hook validations.
- [ ] This PR is fully tested and regression tests are included.
- [ ] Relevant documentation has been updated.

### Additional Information

2023-08-02 14:01 UTC, erdii commented on magefile.go
> +	testCmd := fmt.Sprintf("set -o pipefail; go test -coverprofile=%s -race -test.v=test2json", locations.UnitTestCoverageReport())
shouldn't the `set -o pipefail` be on the bash invocation further down?

2023-08-02 14:55 UTC, erdii commented on magefile.go
> +	must(sh.RunV("bash", "-c", "cat "+locations.UnitTestStdOut()+" | go tool test2json > "+locations.UnitTestExecReport()))
```suggestion
	must(sh.RunV("bash", "-c", "set -o pipefail; cat "+locations.UnitTestStdOut()+" | go tool test2json > "+locations.UnitTestExecReport()))
```

2023-08-02 15:01 UTC, erdii commented on magefile.go
> +	testCmd := fmt.Sprintf("set -o pipefail; go test -coverprofile=%s -race -test.v=test2json", locations.UnitTestCoverageReport())
```suggestion
	testCmd := fmt.Sprintf("set -o pipefail; go test -coverprofile=%s -race -test.v=test2json ./internal/... ./cmd/... ./apis/... | tee %s", locations.UnitTestCoverageReport(), locations.UnitTestStdOut())
```

2023-08-02 15:06 UTC, erdii commented on magefile.go
> +	must(sh.RunV("bash", "-c", "cat "+locations.UnitTestStdOut()+" | go tool test2json > "+locations.UnitTestExecReport()))
```suggestion
	must(sh.RunV("bash", "-c", "set -o pipefail; cat "+locations.UnitTestStdOut()+" | go tool test2json > "+locations.UnitTestExecReport()))
```

2023-08-03 09:20 UTC, eqrx requested changes

2023-08-03 09:20 UTC, eqrx commented on docs/api-reference.md
> +  namespace: default
This file is not part of the PR

2023-08-09 09:53 UTC, erdii approved these changes
/lgtm
/approve

2023-08-09 10:06 UTC, merged