Make probing a public package.
package-operator/package-operator pull request #545
Opened 2023-10-13 13:35 UTC by thetechnick

### Summary
Moves the `package-operator.run/internal/probing` package to be public under `package-operator.run/pkg/probing`.

### Change Type

Refactoring

### Check List Before Merging

- [x] This PR passes all pre-commit hook validations.
- [x] This PR is fully tested and regression tests are included.
- [x] Relevant documentation has been updated.

### Additional Information

2023-10-13 15:50 UTC, eqrx requested changes

2023-10-13 15:50 UTC, eqrx commented on go.mod
> +replace package-operator.run/pkg => ./pkg
suggest does not work for some reason: 
```
replace (
package-operator.run/apis => ./apis
package-operator.run/pkg => ./pkg
)
```

2023-10-13 15:50 UTC, eqrx commented on internal/controllers/objectsetphases/objectsetphase_reconciler.go
> +	internalprobing "package-operator.run/internal/probing"
I suppose we still have some code that we do not want to push to the submodule since we do not want to guarantee stability, right?

2023-10-13 15:50 UTC, eqrx commented on pkg/probing/fieldsequal.go
> +// FieldsEqualProbe checks if the values of the fields under the given json paths are equal.
Do we want to enable docs linters for the probing package? I get that we do not want it in the main module but it could be nice here

2023-10-16 09:12 UTC, erdii commented on go.mod
> +replace package-operator.run/pkg => ./pkg
```suggestion
replace (
	package-operator.run/apis => ./apis
	package-operator.run/pkg => ./pkg
```

2023-10-18 12:16 UTC, eqrx commented on go.mod
> +replace package-operator.run/pkg => ./pkg
josh managed to add that as an actual suggestion block :D

2023-10-20 12:17 UTC, eqrx approved these changes

2023-10-20 12:20 UTC, merged