Add lll linter
package-operator/package-operator pull request #574
Opened 2023-10-19 15:47 UTC by eqrx

Enable the golangci-lint `lll` linters which ensures that code lines may not be longer that 120 chars (non whitespace)

2023-10-23 08:31 UTC, erdii commented on internal/controllers/hostedclusters/hostedcluster_controller.go
> +// From https://github.com/openshift/hypershift/blob/v0.1.13/hypershift-operator/controllers/manifests/manifests.go#L16
Nit: Tags can move. Commits hashes can't.

2023-10-23 08:33 UTC, erdii commented on internal/controllers/objectdeployments/adapter_test.go
> +			},
Why not 

```suggestion
			expectedObjectIDs: []string{
				"/ConfigMap/namespace1/cm1",
				"/ConfigMap/namespace2/cm2",
				"apps/Deployment/default/deployment1",
				"/Secret/default/secret1",
			},
```

?

To me that is way easier to read when glancing over and searching for "that one string"

2023-10-23 08:33 UTC, erdii commented on internal/controllers/objectdeployments/adapter_test.go
> +			},
:bookmark:

2023-10-23 08:36 UTC, erdii commented on internal/controllers/objectsetphases/objectsetphase_controller.go
> +		).Complete(c)
What do you think of
```suggestion
		WatchesRawSource(
			c.dynamicCache.Source(),
			c.ownerStrategy.EnqueueRequestForOwner(objectSetPhase, mgr.GetRESTMapper(), false),
		).Complete(c)
```

2023-10-23 08:40 UTC, erdii commented
I stopped reviewing this PR halfway through because this is essentially 2 PRs in one and each of them touches so many lines that I had a hard time keeping track of everything:

1. adding lll and fixing line length accordingly
2. replacing all instances of `inferface{}` with `any`

Can you please split them into separate PRs? :pray:

2023-10-23 08:41 UTC, erdii requested changes
^

2023-10-24 11:32 UTC, eqrx commented
Split the PRs apart

2024-01-16 16:04 UTC, merged