Setup linter for import aliases
package-operator/package-operator pull request #589
Opened 2023-10-21 11:12 UTC by eqrx

### Summary

### Change Type

### Check List Before Merging

- [ ] This PR passes all pre-commit hook validations.
- [ ] This PR is fully tested and regression tests are included.
- [ ] Relevant documentation has been updated.

### Additional Information

2023-10-23 13:29 UTC, erdii commented
This PR contains a commit that is contained in #588 right? Won't this mess with git history in weird ways?

2023-10-24 11:25 UTC, eqrx commented
@erdii why would it? thats what git is for or not? :D

2023-10-26 11:31 UTC, erdii commented on cmd/remote-phase-manager/main.go
> +	"k8s.io/client-go/scale/scheme"
This imports another package now. Is this change on purpose or an autoimporter fail?

2023-10-26 15:31 UTC, erdii commented on internal/packages/packagecontent/topackage_test.go
> +	apis "package-operator.run/apis"
```suggestion
	"package-operator.run/apis"
```

2023-10-26 15:34 UTC, erdii requested changes
Finally viewed all files :muscle: 

Fix the nit and you'll have my seal of approval :)

2023-10-26 15:42 UTC, erdii approved these changes

2023-10-26 15:58 UTC, merged