Bump go to v1.21
package-operator/package-operator pull request #627
Opened 2023-11-01 14:25 UTC by robshelly

### Summary

Update Go to Version 1.21.
 This [commit](https://github.com/package-operator/package-operator/commit/50e01a93171d9036cebfbd38ea72bdff67bb1ebd#diff-0d20884d33c3fe4132b4dddbb12a73fa7934bd38e0ca73865357683dbbc74d8f) introduced the `slices` package which was introduced to Golang in v.1.21.

https://github.com/package-operator/package-operator/blob/58d4aaf9cd4cc8bdfcd19455c21a82c26a3eec8b/internal/packages/internal/packagevalidation/validation.go#L6

### Change Type

### Check List Before Merging

- [ ] This PR passes all pre-commit hook validations.
- [ ] This PR is fully tested and regression tests are included.
- [ ] Relevant documentation has been updated.

### Additional Information

2023-11-01 15:13 UTC, eqrx commented
- Please use the version `1.21.3` since `1.21.2´ contains a CVE
- Please also update the go.mod version of the submodules `apis/` and `pkg/` 
- Please let the github ci use 1.21.3

2023-11-01 15:13 UTC, eqrx requested changes
Please use the version 1.21.3 since `1.21.2´ contains a CVE
Please let the github ci use 1.21.3

2023-11-01 15:18 UTC, eqrx requested changes

2023-11-01 15:18 UTC, eqrx commented on go.mod
> +go 1.21
```suggestion
go 1.21.3
```

2023-11-01 15:18 UTC, eqrx commented on apis/go.mod
> +go 1.21
```suggestion
go 1.21.3
```

2023-11-01 15:18 UTC, eqrx commented on go.work
> +go 1.21
```suggestion
go 1.21.3
```

2023-11-01 15:18 UTC, eqrx commented on pkg/go.mod
> +go 1.21
```suggestion
go 1.21.3
```

2023-11-01 15:22 UTC, eqrx commented on apis/go.mod
> +go 1.21
(<1.21.3 contains a cve)

2023-11-01 16:10 UTC, robshelly commented
Thanks @eqrx. I've added those changes.

2023-11-02 00:01 UTC, eqrx approved these changes

2023-11-02 00:19 UTC, merged