Add build subcommand to kubectl-package.
package-operator/package-operator pull request #96
Opened 2022-11-22 16:52 UTC by eqrx

This commands builds a source directory into a container image and pushes it to a given destination.

2022-11-22 23:40 UTC, thetechnick commented on internal/cli/build/build.go
> +	rawLayer := map[string][]byte{}
Important: please put all files into a /package directory.
I've tried it top-level at first as well, but all the linux directories like /etc /dev and sysfs are cluttering root and make loading difficult.

2022-11-24 23:54 UTC, thetechnick commented
@eqrx what do you think about the way kubectl is structuring it's commands:
E.g. https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/taint/taint.go

It separates cobra configuration code from options and their validation. I quite like it, because testing becomes very straightforward as it's not as intertwined with cobra.

2022-11-25 11:39 UTC, eqrx commented
@thetechnick I see the benefit but I am not sure if this would e a benefit right now since the complexity of our commands is relatively low. I cut down the complexity of the build subcommand in the last push to 25 lines, ptal. Would you still say it would be beneficial now?

Right now I would argue that pulling the command definition and the validation apart makes it harder to read

2022-11-25 13:06 UTC, eqrx commented
nvm, have implemented something like it :D

is it close enough for kubectl for you or do you want what they do in verbatim?

2022-11-28 10:13 UTC, thetechnick requested changes

2022-11-28 13:44 UTC, thetechnick approved these changes

2022-11-28 13:49 UTC, merged